project:
  type: website
  output-dir: docs
website:
  title: "Chloe M. Hall, Ph.D."
  navbar:
    left:
      - href: index.qmd
        text: Home
      #- about.qmd
      - contact.qmd
      - images.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

